### ISSUE TITLE
macOS hosts file processing error

### ISSUE THREAD

**Issue by grylem** [lucascaro/hostman#3]
Hi
if the file contains a string
fe80::1%lo0          localhost
any actions give a message:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse(BadIp(AddrParseError(()), "fe80::1%lo0"))', src/libcore/result.rs:997:5
Regards.

**Comment by lucascaro** [comment]
I'll check it out, thanks!

**Comment by lucascaro** [comment]
looks like a bug in the parse host library I'm using. I'll try a different one, thanks for reporting!

**Comment by lucascaro** [comment]
fixed in the last release, thanks
