### ISSUE TITLE
Rust 1.36 breakage, due to use of parse-hosts/multistr/bow

### ISSUE THREAD

**Issue by pnkfelix** [lucascaro/hostman#4]
Spawned off of rust-lang/rust#61471

The [`bow` crate](https://crates.io/crates/bow) has been marked as deprecated. The repository link for the `bow` crate is a dead link, and the author of the crate indicates that it should not be used. (The crate broke due to PR rust-lang/rust#49799, which is currently part of the beta release, Rust 1.36)

Downstream from `bow` crate are other crates by the same author: [`multistr`, `parse-hosts`, `swc-hosts`]; I am assuming these three crates will *not* be updated to use something other than `bow`. (This is entirely an assumption on my part; their metadata on crates.io does not indicate anything about there current or future status, thought they do break under Rust 1.36.)

*This* crate (`hostman`) does currently depend on `parse-hosts` currently. So `hostman` will break when Rust 1.36 goes from beta to stable.

I think it will be necessary for this crate to stop using `parse-hosts`. That, or make a fork of `parse-hosts` (and `multistr` and `bow`) and update them to work with Rust 1.36...

**Comment by lucascaro** [comment]
Thanks for reporting! The plan is to stop using `parse-hosts` but I haven't made the time to do it yet.

**Comment by lucascaro** [comment]
removed the dependency in the last release, thanks!
